create or replace PROCEDURE SP_CVM_CA_CANDIDATOS AS 
BEGIN 

    -- Generacioon de Candidatos Parte 1: Obtener la base cierre al uultimo mes, con los filtros acordados con el negocio.
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CVM_EMP_INF.CVM_CA_CANDIDATOS_000'; 
    INSERT INTO CVM_CA_CANDIDATOS_000 
        SELECT 
        NUMPERIODO,                       
        FECINGRESOCLIENTE,      
        VCHRUCCOMPANIA,         
        VCHTELEFONO,            
        VCHESTADOCONTRATO,      
        FECACTIVACIONCONTRATO,  
        NUMCODCONTRATOBSCS,     
        VCHTECNOLOGIA,          
        VCHTECNOCOMERCIAL,      
        VCHPACKCHIP,            
        VCHNUEVOSEGMENTO,       
        VCHIMEI,  
        VCHPLANTARIFARIO,
        NUMCODPLANTARIFARIOBSCS,
        VCHGERENCIA2,
        VCHCANALVENTA,
        VCHZONAVENTA,
        VCHSEGMENTO_2021,       
        VCHSUBSEGMENTO_2021,    
        VCH_GOBIERNO_2021
        FROM ODS_INF.HOM_BASESUSCRIPTOR 
        WHERE 
        NUMPERIODO = (SELECT MAX(NUMPERIODO) FROM ODS_INF.HOM_BASESUSCRIPTOR)
        AND TRIM(UPPER(VCHESTADOCONTRATO)) LIKE '%ACTIVO%'
        AND SUBSTR(VCHRUCCOMPANIA,1,2) = 20
        AND LENGTH(VCHRUCCOMPANIA) = 11;

    -- Agregando las altas
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CVM_EMP_INF.CVM_CA_CANDIDATOS_001';
    INSERT INTO CVM_CA_CANDIDATOS_001 
        SELECT 
        NUMPERIODO,                       
        FECINGRESOCLIENTE,      
        VCHRUCCOMPANIA,         
        VCHTELEFONO,            
        VCHESTADOCONTRATO,      
        FECACTIVACIONCONTRATO,  
        NUMCODCONTRATOBSCS,     
        VCHTECNOLOGIA,          
        VCHTECNOCOMERCIAL,      
        VCHPACKCHIP,            
        VCHNUEVOSEGMENTO,       
        VCHIMEI,  
        VCHPLANTARIFARIO,
        NUMCODPLANTARIFARIOBSCS,
        VCHGERENCIA2,
        VCHCANALVENTA,
        VCHZONAVENTA,
        VCHSEGMENTO_2021,       
        VCHSUBSEGMENTO_2021,    
        VCH_GOBIERNO_2021
        FROM CVM_CA_CANDIDATOS_000
        UNION
        SELECT 
        NUMPERIODO,
        NULL FECINGRESOCLIENTE, 
        VCHDOCUMENTO VCHRUCCOMPANIA,
        VCHTELEFONO,
        'Activo' VCHESTADOCONTRATO, 
        FECACTIV FECACTIVACIONCONTRATO,
        NUMCODCONTRATOBSCS,     
        NULL VCHTECNOLOGIA,          
        VCHDIVISION VCHTECNOCOMERCIAL,     -- Division a Tecnología comercial. Tener mapeado este campo para cualquier query con referente a tecnología.
        VCHTIPOEQUIPO VCHPACKCHIP,
        VCHNUEVOSEGMENTO,
        NULL VCHIMEI,
        VCHPLANTARIFARIO,
        NUMTMCODE NUMCODPLANTARIFARIOBSCS,
        VCHGERENCIA2,
        VCHCANALVENTA,
        VCHZONAVENTA,
        VCHSEGMENTO_2021,
        VCHSUBSEGMENTO_2021,
        VCH_GOBIERNO_2021
        FROM HOD_BASEVENTA 
        WHERE SUBSTR(VCHDOCUMENTO,1,2) = 20
        AND LENGTH(VCHDOCUMENTO) = 11;

    -- Quitando aquellos que desactivaron.
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CVM_EMP_INF.CVM_CA_CANDIDATOS_002';
    INSERT INTO CVM_CA_CANDIDATOS_002
        SELECT * FROM CVM_CA_CANDIDATOS_001 
        WHERE VCHTELEFONO NOT IN (SELECT VCHTELEFONO FROM HOD_DESACTIVACION);

    -- Insights (Para Renos)
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CVM_EMP_INF.CVM_CA_CANDIDATOS_003';
    INSERT INTO CVM_CA_CANDIDATOS_003
        SELECT * FROM (SELECT 
        VCHRUCCOMPANIA,
        VCHTELEFONO,
        VCHPACKCHIP,
        FECACTIVACIONCONTRATO,
        VCHTECNOCOMERCIAL,
        MESES_CLIENTE,
        MESES_ULT_RENO,
        CASE 
        WHEN VCHPACKCHIP = 'SIM' AND MESES_ULT_RENO IS NOT NULL THEN 'PACK'
        ELSE VCHPACKCHIP
        END NEW_VCHPACKCHIP,
        CASE 
        WHEN MESES_ULT_RENO IS NULL THEN MESES_CLIENTE
        ELSE MESES_ULT_RENO 
        END NEW_MESES_CLIENTE
        FROM (SELECT 
            A.VCHRUCCOMPANIA,
            A.VCHTELEFONO,
            A.VCHPACKCHIP,
            A.FECACTIVACIONCONTRATO,
            A.VCHTECNOCOMERCIAL,
            CEIL(MONTHS_BETWEEN(SYSDATE, TO_DATE(TO_CHAR(FECACTIVACIONCONTRATO, 'DD/MM/YY'), 'DD/MM/YY'))) MESES_CLIENTE,
            CEIL(MONTHS_BETWEEN(SYSDATE, TO_DATE(R.FECHACIERREORDEN, 'DD/MM/YYYY HH24:MI:SS'))) MESES_ULT_RENO
            -- Meses desde la última renovación
            FROM CVM_CA_CANDIDATOS_002 A 
            LEFT JOIN p_Renovacion R
            ON A.VCHRUCCOMPANIA = R.RUCCOMPANIA AND A.VCHTELEFONO = R.TELEFONO)
            order by meses_cliente desc) WHERE LENGTH(VCHTELEFONO) >= 8 AND VCHTECNOCOMERCIAL = '3G';
   

END;